import type { Category, Question } from "./types";

export const categoryLabels: Record<Category, string> = {
  bible: "Bible",
  food: "Food",
  animals: "Animals",
  holidays: "Holidays",
  office: "Office / Workplace",
};

export const questionBank: Record<Category, Question[]> = {
  bible: [
    { answer: "Noah", alternateAnswers: [], clue1: "He was 600 years old at a pivotal moment", clue2: "He built something massive out of wood", clue3: "He loaded animals two by two" },
    { answer: "Moses", alternateAnswers: [], clue1: "He once had a speech impediment", clue2: "He spent 40 years in the wilderness", clue3: "He parted the Red Sea" },
    { answer: "David", alternateAnswers: [], clue1: "He was the youngest of eight brothers", clue2: "He was a skilled harp player", clue3: "He defeated Goliath with a sling" },
    { answer: "Jonah", alternateAnswers: [], clue1: "He tried to flee to Tarshish", clue2: "He was thrown overboard during a storm", clue3: "He was swallowed by a great fish" },
    { answer: "Samson", alternateAnswers: [], clue1: "He once ate honey from an unusual source", clue2: "A woman betrayed his secret", clue3: "His strength was in his long hair" },
    { answer: "Abraham", alternateAnswers: ["Abram"], clue1: "He originally came from Ur", clue2: "God changed his name", clue3: "He is called the father of many nations" },
    { answer: "Daniel", alternateAnswers: [], clue1: "He refused to eat the king's food", clue2: "He interpreted mysterious writing on a wall", clue3: "He survived a night in a den of lions" },
    { answer: "Solomon", alternateAnswers: [], clue1: "He authored many proverbs", clue2: "He built the first temple in Jerusalem", clue3: "He asked God for wisdom instead of riches" },
    { answer: "Esther", alternateAnswers: [], clue1: "She kept her heritage a secret", clue2: "She risked her life to approach a king uninvited", clue3: "She saved her people from Haman's plot" },
    { answer: "Peter", alternateAnswers: ["Simon Peter", "Simon"], clue1: "He once sank while attempting the impossible", clue2: "He denied someone three times before a rooster crowed", clue3: "Jesus called him 'the rock'" },
    { answer: "Joseph", alternateAnswers: [], clue1: "He was sold for twenty pieces of silver", clue2: "He interpreted dreams while in prison", clue3: "He had a coat of many colors" },
    { answer: "Ruth", alternateAnswers: [], clue1: "She was a Moabite by birth", clue2: "She gleaned grain in the fields", clue3: "She said 'Where you go I will go'" },
    { answer: "Elijah", alternateAnswers: [], clue1: "Ravens brought him food", clue2: "He challenged 450 prophets on a mountain", clue3: "He was taken to heaven in a chariot of fire" },
    { answer: "Paul", alternateAnswers: ["Saul"], clue1: "He was a tentmaker by trade", clue2: "He wrote letters to churches from prison", clue3: "He was blinded on the road to Damascus" },
    { answer: "Adam", alternateAnswers: [], clue1: "He was the first to name things", clue2: "He lived in a perfect garden", clue3: "He was made from the dust of the ground" },
  ],

  food: [
    { answer: "Avocado", alternateAnswers: [], clue1: "Its name comes from an Aztec word", clue2: "It turns brown quickly when exposed to air", clue3: "It's the main ingredient in guacamole" },
    { answer: "Sushi", alternateAnswers: [], clue1: "It was originally a preservation method", clue2: "Vinegar-seasoned grain is essential", clue3: "Japanese dish often made with raw fish and rice" },
    { answer: "Pizza", alternateAnswers: [], clue1: "A queen in 1889 inspired a famous variety", clue2: "Naples, Italy is considered its birthplace", clue3: "Round dough topped with cheese and tomato sauce" },
    { answer: "Chocolate", alternateAnswers: [], clue1: "The Aztecs used it as currency", clue2: "It starts as a bean in a tropical pod", clue3: "Sweet treat made from cacao — comes in milk, dark, and white" },
    { answer: "Banana", alternateAnswers: [], clue1: "It's technically classified as a berry", clue2: "It's the world's most popular fruit by trade volume", clue3: "A yellow curved fruit that monkeys love" },
    { answer: "Honey", alternateAnswers: [], clue1: "Archaeologists found edible jars of it in Egyptian tombs", clue2: "It never spoils naturally", clue3: "Sweet golden syrup made by bees" },
    { answer: "Pretzel", alternateAnswers: [], clue1: "Monks may have invented it as a reward for prayers", clue2: "Its shape is said to represent arms crossed in prayer", clue3: "Twisted bread snack often topped with salt" },
    { answer: "Popcorn", alternateAnswers: [], clue1: "Evidence of it was found in 5,000-year-old caves", clue2: "Moisture inside causes it to explode", clue3: "Puffed corn kernels — a classic movie snack" },
    { answer: "Pancake", alternateAnswers: ["Pancakes"], clue1: "Ancient Greeks made a version with wheat and olive oil", clue2: "There's a holiday where people race while flipping them", clue3: "Flat breakfast cake cooked on a griddle, served with syrup" },
    { answer: "Mango", alternateAnswers: ["Mangoes"], clue1: "It's the national fruit of India, Pakistan, and the Philippines", clue2: "There are over 500 varieties worldwide", clue3: "Tropical orange fruit with a large pit in the center" },
    { answer: "Taco", alternateAnswers: ["Tacos"], clue1: "Silver miners in Mexico may have coined the name", clue2: "Tuesday is its unofficial day in America", clue3: "Mexican folded tortilla filled with meat and toppings" },
    { answer: "Donut", alternateAnswers: ["Doughnut", "Donuts", "Doughnuts"], clue1: "A sea captain's mother may have invented its hole", clue2: "Police officers are stereotypically associated with it", clue3: "Ring-shaped fried dough covered in glaze or sprinkles" },
    { answer: "Cheese", alternateAnswers: [], clue1: "Legend says it was discovered accidentally in a sheep's stomach", clue2: "Wisconsin and France are both famous for making it", clue3: "Dairy product that comes in cheddar, brie, and gouda" },
    { answer: "Waffle", alternateAnswers: ["Waffles"], clue1: "Medieval European communion irons inspired its pattern", clue2: "Belgium is famous for two different styles of it", clue3: "Grid-patterned breakfast item you pour syrup into" },
    { answer: "Cinnamon", alternateAnswers: [], clue1: "It was once more valuable than gold", clue2: "It comes from the bark of a tropical tree", clue3: "Brown spice used in rolls, lattes, and apple pie" },
    { answer: "Olive", alternateAnswers: ["Olives"], clue1: "A branch of this plant symbolizes peace", clue2: "The Mediterranean region produces most of the world's supply", clue3: "Small fruit pressed to make a popular cooking oil" },
  ],

  animals: [
    { answer: "Elephant", alternateAnswers: ["Elephants"], clue1: "It can detect seismic vibrations through its feet", clue2: "It never forgets, according to the saying", clue3: "Largest land animal with a trunk and big ears" },
    { answer: "Octopus", alternateAnswers: [], clue1: "It has three hearts and blue blood", clue2: "It can change color and squeeze through tiny gaps", clue3: "Sea creature with eight arms" },
    { answer: "Penguin", alternateAnswers: ["Penguins"], clue1: "Males of one species balance an egg on their feet for months", clue2: "They live mostly in the Southern Hemisphere", clue3: "Tuxedo-colored bird that cannot fly but swims" },
    { answer: "Giraffe", alternateAnswers: ["Giraffes"], clue1: "Its heart weighs about 25 pounds", clue2: "No two have the same pattern of spots", clue3: "Tallest living animal with a very long neck" },
    { answer: "Dolphin", alternateAnswers: ["Dolphins"], clue1: "It sleeps with one eye open — literally half its brain rests", clue2: "It uses echolocation to navigate and hunt", clue3: "Intelligent, playful ocean mammal known for jumping" },
    { answer: "Chameleon", alternateAnswers: ["Chameleons"], clue1: "Its tongue can be twice its body length", clue2: "Its eyes move independently of each other", clue3: "Lizard famous for changing its skin color" },
    { answer: "Kangaroo", alternateAnswers: ["Kangaroos"], clue1: "Its babies are born the size of a jellybean", clue2: "It cannot walk backwards easily", clue3: "Australian animal that hops and carries babies in a pouch" },
    { answer: "Flamingo", alternateAnswers: ["Flamingos"], clue1: "They are born white or gray", clue2: "Their diet is what makes them colorful", clue3: "Tall pink bird that stands on one leg" },
    { answer: "Sloth", alternateAnswers: ["Sloths"], clue1: "Algae grows on its fur, providing camouflage", clue2: "It sleeps up to 20 hours a day", clue3: "Extremely slow-moving animal that hangs from trees" },
    { answer: "Platypus", alternateAnswers: [], clue1: "Scientists initially thought it was a hoax when first described", clue2: "Males have a venomous spur on their hind legs", clue3: "Duck-billed, beaver-tailed mammal that lays eggs" },
    { answer: "Owl", alternateAnswers: ["Owls"], clue1: "It cannot move its eyeballs — they're tube-shaped", clue2: "Its flight feathers are designed for silent flying", clue3: "Nocturnal bird that hoots and can rotate its head" },
    { answer: "Seahorse", alternateAnswers: ["Seahorses"], clue1: "They are among the slowest swimmers in the ocean", clue2: "The male carries the babies in its pouch", clue3: "Small ocean creature shaped like a chess knight" },
    { answer: "Cheetah", alternateAnswers: ["Cheetahs"], clue1: "It can accelerate from 0 to 60 mph in three seconds", clue2: "It purrs but cannot roar like other big cats", clue3: "Spotted wild cat — the fastest land animal" },
    { answer: "Koala", alternateAnswers: ["Koalas"], clue1: "It sleeps 18-22 hours a day due to its low-energy diet", clue2: "It has fingerprints remarkably similar to humans", clue3: "Australian tree-dweller that eats eucalyptus leaves" },
    { answer: "Bee", alternateAnswers: ["Bees", "Honeybee", "Honey bee"], clue1: "It communicates through a waggle dance", clue2: "A colony can produce over 100 pounds of its product yearly", clue3: "Black and yellow insect that pollinates flowers and makes honey" },
    { answer: "Parrot", alternateAnswers: ["Parrots"], clue1: "Some species can live over 80 years", clue2: "Pirates are stereotypically shown with one on their shoulder", clue3: "Colorful tropical bird that can mimic human speech" },
  ],

  holidays: [
    { answer: "Christmas", alternateAnswers: ["Xmas"], clue1: "The modern version of its icon was shaped by a soda company ad campaign", clue2: "A star or angel usually sits on top of a decorated tree", clue3: "December 25th — gifts, stockings, and Santa Claus" },
    { answer: "Halloween", alternateAnswers: [], clue1: "It evolved from the ancient Celtic festival Samhain", clue2: "People carve faces into orange gourds", clue3: "October 31st — trick-or-treating in costumes" },
    { answer: "Easter", alternateAnswers: [], clue1: "Its date changes every year based on the moon", clue2: "Children search for hidden colorful eggs", clue3: "Spring holiday celebrating the resurrection of Jesus" },
    { answer: "Thanksgiving", alternateAnswers: [], clue1: "The first one lasted three days, not one", clue2: "A presidential pardon saves a bird each year", clue3: "November holiday with turkey, stuffing, and gratitude" },
    { answer: "Valentine", alternateAnswers: ["Valentines", "Valentine's Day", "Valentines Day"], clue1: "It may be linked to a Roman festival called Lupercalia", clue2: "It's the biggest day of the year for card sales", clue3: "February 14th — hearts, roses, and love" },
    { answer: "Independence Day", alternateAnswers: ["Fourth of July", "July Fourth", "4th of July"], clue1: "Most signatures on the document came weeks after the declared date", clue2: "John Adams predicted celebrations with bonfires and illuminations", clue3: "July 4th — fireworks celebrating America's birthday" },
    { answer: "New Year", alternateAnswers: ["New Years", "New Year's", "New Years Eve"], clue1: "The earliest known celebrations were in Mesopotamia around 2000 BC", clue2: "A famous ball drops at midnight in Times Square", clue3: "January 1st — the start of a brand new year" },
    { answer: "St. Patrick", alternateAnswers: ["St Patrick", "Saint Patrick", "St Patricks Day", "St. Patrick's Day", "Saint Patricks Day"], clue1: "The original color associated with this person was blue, not green", clue2: "Legend says he drove all snakes out of Ireland", clue3: "March 17th — wearing green, shamrocks, and Irish pride" },
    { answer: "Hanukkah", alternateAnswers: ["Chanukah", "Hannukah", "Hanukah"], clue1: "A small amount of oil miraculously burned for eight nights", clue2: "A special nine-branched candelabrum is lit each night", clue3: "Jewish festival of lights lasting eight days" },
    { answer: "Cinco de Mayo", alternateAnswers: ["Cinco De Mayo"], clue1: "It commemorates a military victory, not a country's independence", clue2: "A smaller army defeated a much larger French force in 1862", clue3: "May 5th — Mexican holiday celebrating the Battle of Puebla" },
    { answer: "Mother's Day", alternateAnswers: ["Mothers Day", "Mother Day"], clue1: "Its founder later protested against the holiday's commercialization", clue2: "It's one of the busiest days for restaurants in the US", clue3: "A Sunday in May to celebrate and honor moms" },
    { answer: "Labor Day", alternateAnswers: ["Labour Day"], clue1: "It started during a period of labor union strikes in the 1880s", clue2: "It unofficially marks the end of summer", clue3: "First Monday of September honoring American workers" },
    { answer: "Groundhog Day", alternateAnswers: ["Groundhog"], clue1: "A popular 1993 movie shares this day's name", clue2: "A furry animal's shadow supposedly predicts the weather", clue3: "February 2nd — Punxsutawney Phil predicts spring" },
    { answer: "April Fools", alternateAnswers: ["April Fools Day", "April Fool's Day", "April Fool"], clue1: "Some historians trace it to France's calendar change in 1582", clue2: "News outlets sometimes publish fake stories on this day", clue3: "April 1st — pranks, jokes, and hoaxes" },
    { answer: "Diwali", alternateAnswers: ["Deepavali"], clue1: "It symbolizes the victory of light over darkness", clue2: "Families light rows of clay oil lamps", clue3: "Hindu festival of lights with fireworks and sweets" },
  ],

  office: [
    { answer: "Stapler", alternateAnswers: [], clue1: "King Louis XV owned a custom-made one", clue2: "A red one starred in a famous comedy movie", clue3: "Desktop device that fastens papers together with metal" },
    { answer: "Coffee", alternateAnswers: [], clue1: "Legend says an Ethiopian goat herder discovered it", clue2: "Finland consumes the most of it per capita", clue3: "Hot caffeinated drink brewed from roasted beans" },
    { answer: "Email", alternateAnswers: ["E-mail"], clue1: "The first one was sent in 1971 as a test", clue2: "The @ symbol is essential to its format", clue3: "Digital messages sent through the internet" },
    { answer: "Meeting", alternateAnswers: ["Meetings"], clue1: "Studies show most of them could have been a written message", clue2: "An agenda is supposed to guide it but rarely does", clue3: "A scheduled gathering where coworkers discuss work" },
    { answer: "Spreadsheet", alternateAnswers: ["Spreadsheets", "Excel"], clue1: "VisiCalc was the first electronic version in 1979", clue2: "Rows are numbers, columns are letters", clue3: "Grid of cells for organizing data — think Excel" },
    { answer: "Deadline", alternateAnswers: ["Deadlines"], clue1: "The word originally referred to a line in a Civil War prison", clue2: "It causes the most workplace stress, studies say", clue3: "The final date by which work must be completed" },
    { answer: "Printer", alternateAnswers: [], clue1: "The first laser one was built at Xerox in 1969", clue2: "It's always jamming at the worst possible time", clue3: "Office machine that puts digital documents onto paper" },
    { answer: "Keyboard", alternateAnswers: [], clue1: "The QWERTY layout was designed in 1873 for typewriters", clue2: "It can harbor more germs than a toilet seat", clue3: "Input device with letter and number keys for typing" },
    { answer: "Whiteboard", alternateAnswers: ["White board"], clue1: "A photographer accidentally discovered the surface worked with markers", clue2: "Brainstorming sessions almost always involve one", clue3: "Large white surface on the wall you write on with dry-erase markers" },
    { answer: "Lunch break", alternateAnswers: ["Lunch", "Lunchbreak"], clue1: "Many countries legally mandate a minimum duration for it", clue2: "Eating at your desk means you're skipping it", clue3: "Midday pause from work to eat a meal" },
    { answer: "Password", alternateAnswers: ["Passwords"], clue1: "'123456' was the most common one for years running", clue2: "IT departments beg you to make it stronger", clue3: "Secret word or phrase you type to log in" },
    { answer: "Sticky note", alternateAnswers: ["Sticky notes", "Post-it", "Post-it note", "Postit"], clue1: "It was invented by accident when a glue formula failed", clue2: "3M's most famous product comes in a signature yellow", clue3: "Small colored paper with adhesive backing for reminders" },
    { answer: "Promotion", alternateAnswers: [], clue1: "Peter's Principle says everyone rises to their level of incompetence through these", clue2: "It usually comes with a new title and more responsibility", clue3: "Moving up to a higher position at work" },
    { answer: "Commute", alternateAnswers: ["Commuting"], clue1: "The average American spends about 27 minutes on one each way", clue2: "Remote work eliminated it for many people", clue3: "The daily trip between home and the office" },
    { answer: "Resume", alternateAnswers: ["CV", "Résumé"], clue1: "Leonardo da Vinci is credited with creating the first one in 1482", clue2: "Recruiters spend an average of 7 seconds scanning one", clue3: "Document listing your work experience for job applications" },
    { answer: "Intern", alternateAnswers: ["Internship"], clue1: "The practice dates back to medieval apprenticeships", clue2: "Whether they should be paid is a hot debate", clue3: "A temporary junior worker gaining experience at a company" },
  ],
};
